const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getData: () => ipcRenderer.invoke('get-data'),
  getActivity: () => ipcRenderer.invoke('get-activity'),
  getPcStatus: () => ipcRenderer.invoke('get-pc-status'),
  getUsbStorageBlocked: () => ipcRenderer.invoke('get-usb-storage-blocked'),
  setUsbStorageBlocked: (blocked) => ipcRenderer.invoke('set-usb-storage-blocked', blocked),
  getInstalledApps: () => ipcRenderer.invoke('get-installed-apps'),
  openAppUninstaller: () => ipcRenderer.invoke('open-app-uninstaller'),
  installWindowsUpdates: () => ipcRenderer.invoke('install-windows-updates'),
  getWindowsUpdateInstallStatus: (jobId) => ipcRenderer.invoke('get-windows-update-install-status', jobId),
  selectPcFolder: () => ipcRenderer.invoke('select-pc-folder'),
  listPcFiles: (relativePath) => ipcRenderer.invoke('list-pc-files', relativePath),
  deletePcFile: (relativePath) => ipcRenderer.invoke('delete-pc-file', relativePath),
  restartPc: () => ipcRenderer.invoke('restart-pc'),
  flushDns: () => ipcRenderer.invoke('flush-dns'),
  setHotspotSharingDisabled: (disabled) => ipcRenderer.invoke('set-hotspot-sharing-disabled', disabled),
  getAppVersion: () => ipcRenderer.invoke('get-app-version'),
  getUpdateStatus: () => ipcRenderer.invoke('get-update-status'),
  setAutomaticUpdates: (enabled) => ipcRenderer.invoke('set-automatic-updates', enabled),
  checkForUpdates: () => ipcRenderer.invoke('check-for-updates'),
  downloadUpdate: () => ipcRenderer.invoke('download-update'),
  installUpdate: () => ipcRenderer.invoke('install-update'),
  onUpdateStatus: (callback) => ipcRenderer.on('update-status', (_event, status) => callback(status)),
  onWindowsUpdateStatus: (callback) => ipcRenderer.on('windows-update-status', (_event, status) => callback(status)),
  updateSites: (sites) => ipcRenderer.invoke('update-sites', sites),
  updateAllowedSites: (sites) => ipcRenderer.invoke('update-allowed-sites', sites),
  updateApps: (apps) => ipcRenderer.invoke('update-apps', apps),
  startLock: (minutes) => ipcRenderer.invoke('start-lock', { minutes }),
  getLockStatus: () => ipcRenderer.invoke('get-lock-status'),
  getSchedules: () => ipcRenderer.invoke('get-schedules'),
  saveSchedule: (schedule) => ipcRenderer.invoke('save-schedule', schedule),
  deleteSchedule: (id) => ipcRenderer.invoke('delete-schedule', id),
  temporaryUnblock: (minutes, sites, apps) => ipcRenderer.invoke('temporary-unblock', { minutes, sites, apps }),
  clearTemporaryUnblock: () => ipcRenderer.invoke('clear-temporary-unblock'),
  remoteCommand: (host, password, command, payload, role) => ipcRenderer.invoke('remote-command', { host, password, command, payload, role }),
  remoteHealth: (host) => ipcRenderer.invoke('remote-health', host),
  openScreenView: (host, name) => ipcRenderer.invoke('open-screen-view', { host, name }),
  openRemotePcWindow: (host, name) => ipcRenderer.invoke('open-remote-pc-window', { host, name }),
  onRemoteScreenEnding: (callback) => ipcRenderer.on('remote-screen-ending', () => callback()),
  openFileSharing: (destinations, availableDestinations, sources) => ipcRenderer.invoke('open-file-sharing', { destinations, availableDestinations, sources }),
  pickAndSendSharedFiles: (hosts) => ipcRenderer.invoke('pick-and-send-shared-files', hosts),
  listSharedFiles: (host) => ipcRenderer.invoke('list-shared-files', host),
  downloadSharedFile: (host, file) => ipcRenderer.invoke('download-shared-file', { host, file }),
  relaySharedFile: (sourceHost, file, destinationHosts) => ipcRenderer.invoke('relay-shared-file', { sourceHost, file, destinationHosts }),
  discoverNetwork: () => ipcRenderer.invoke('discover-network'),
  networkSpeedTest: () => ipcRenderer.invoke('network-speed-test'),
  onNetworkSpeedStage: (callback) => ipcRenderer.on('network-speed-stage', (_event, stage) => callback(stage)),
  getNetworkGroups: () => ipcRenderer.invoke('get-network-groups'),
  saveNetworkGroup: (group) => ipcRenderer.invoke('save-network-group', group),
  deleteNetworkGroup: (groupId) => ipcRenderer.invoke('delete-network-group', groupId),
  onNetworkGroupsUpdated: (callback) => ipcRenderer.on('network-groups-updated', () => callback())
});
